FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mlflow boto3 psycopg2-binary

EXPOSE 5000

# CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]