"""create user data table

Revision ID: 2afd9238e138
Revises: 
Create Date: 2026-08-01 12:16:35.005972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '2afd9238e138'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdata',
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('Medu', sa.Integer(), nullable=False),
    sa.Column('Fedu', sa.Integer(), nullable=False),
    sa.Column('traveltime', sa.Integer(), nullable=False),
    sa.Column('studytime', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('famrel', sa.Integer(), nullable=False),
    sa.Column('freetime', sa.Integer(), nullable=False),
    sa.Column('goout', sa.Integer(), nullable=False),
    sa.Column('Dalc', sa.Integer(), nullable=False),
    sa.Column('Walc', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('absences', sa.Integer(), nullable=False),
    sa.Column('school', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('famsize', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Pstatus', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Mjob', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Fjob', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guardian', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schoolsup', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('famsup', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activities', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nursery', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('higher', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('internet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('romantic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance_category', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdata')
    # ### end Alembic commands ###
